/*
 * Copyright 2025 ZenSpeak
 *
 * D3D11 GPU texture-backed VideoFrameBuffer for zero-copy encoding
 * This allows direct GPU→encoder paths without CPU readback.
 */

#pragma once

#ifdef _WIN32

#include <d3d11.h>
#include <wrl/client.h>
#include <memory>
#include <mutex>
#include <optional>

#include "api/video/video_frame_buffer.h"
#include "api/video/i420_buffer.h"

// Include CXX-generated header for D3D11TextureInfo struct
#include "webrtc-sys/src/d3d11_frame_buffer.rs.h"

namespace livekit_ffi {

/// Forward declaration for CXX bridge
class D3D11FrameBuffer;

// D3D11TextureInfo is defined in d3d11_frame_buffer.rs and generated by CXX

/// D3D11 texture-backed VideoFrameBuffer
/// 
/// This wraps an ID3D11Texture2D and presents it as a WebRTC native frame buffer.
/// Hardware encoders (like NVENC) can detect this type and use the texture directly
/// via D3D11→CUDA interop, avoiding CPU readback.
///
/// Lifetime: The texture must remain valid until this buffer is destroyed.
/// The buffer takes ownership via ComPtr reference counting.
class D3D11TextureBuffer : public webrtc::VideoFrameBuffer {
 public:
  // Internal: key for the global texture pool. Public only so the .cpp can use it
  // as an unordered_map key without friend/anonymous-namespace issues.
  struct PoolKey {
    ID3D11Device* device;
    UINT width;
    UINT height;
    DXGI_FORMAT format;
  };

  /// Create from an existing D3D11 texture.
  ///
  /// Ownership: `texture` must carry a live COM ref. In our Rust GPU pipeline we
  /// transfer ownership across threads by intentionally leaking one AddRef; this
  /// function adopts that ref (does not AddRef again) to avoid per-frame leaks.
  static rtc::scoped_refptr<D3D11TextureBuffer> Create(
      ID3D11Texture2D* texture,
      ID3D11Device* device);
  
  /// Create from a texture and device context (for textures that need staging copy)
  static rtc::scoped_refptr<D3D11TextureBuffer> CreateWithCopy(
      ID3D11Texture2D* source_texture,
      ID3D11Device* device,
      ID3D11DeviceContext* context);

  /// Create from a source texture by copying into a pooled output texture.
  ///
  /// This is used to avoid per-frame `CreateTexture2D` when the producer can provide a
  /// D3D11 device + immediate context on a single thread (capture thread).
  static rtc::scoped_refptr<D3D11TextureBuffer> CreateWithPooledCopy(
      ID3D11Texture2D* source_texture,
      ID3D11Device* device,
      ID3D11DeviceContext* context,
      UINT width,
      UINT height,
      DXGI_FORMAT format);

  /// Create a D3D11 frame buffer by scaling a source texture into a pooled output texture
  /// using the D3D11 Video Processor (video engine) when available.
  ///
  /// This is intended to reduce contention with 3D shader cores (vs pixel-shader scaling)
  /// while preserving lifetime safety (the returned buffer owns a pooled output texture).
  ///
  /// Returns null on failure; callers should fall back to shader scaling + pooled copy.
  static rtc::scoped_refptr<D3D11TextureBuffer> CreateWithPooledVideoProcessorScale(
      ID3D11Texture2D* source_texture,
      ID3D11Device* device,
      ID3D11DeviceContext* context,
      UINT src_width,
      UINT src_height,
      UINT dst_width,
      UINT dst_height,
      DXGI_FORMAT format);

  /// Internal: wrap an already-acquired pooled texture into a `D3D11TextureBuffer` that will
  /// return it to the pool on destruction.
  static rtc::scoped_refptr<D3D11TextureBuffer> CreateFromPooledTexture(
      Microsoft::WRL::ComPtr<ID3D11Texture2D> pooled_texture,
      ID3D11Device* device,
      UINT width,
      UINT height,
      DXGI_FORMAT format);

  ~D3D11TextureBuffer() override;

  // VideoFrameBuffer interface
  Type type() const override { return Type::kNative; }
  int width() const override { return width_; }
  int height() const override { return height_; }

  /// GPU-backed crop + scale.
  ///
  /// WebRTC calls this when adaptation (degradation) requests a smaller frame.
  /// The default implementation for native buffers falls back to ToI420(), which
  /// defeats zero-copy and can cause quality/perf regressions.
  rtc::scoped_refptr<webrtc::VideoFrameBuffer> CropAndScale(
      int offset_x,
      int offset_y,
      int crop_width,
      int crop_height,
      int scaled_width,
      int scaled_height) override;
  
  /// Convert to I420 (performs GPU→CPU readback as fallback)
  rtc::scoped_refptr<webrtc::I420BufferInterface> ToI420() override;

  /// Get the underlying D3D11 texture (for hardware encoders)
  ID3D11Texture2D* texture() const { return texture_.Get(); }
  
  /// Get the D3D11 device associated with this texture
  ID3D11Device* device() const { return device_.Get(); }
  
  /// Get the DXGI format of the texture
  DXGI_FORMAT format() const { return format_; }
  
  /// Get texture info for FFI
  D3D11TextureInfo GetInfo() const;
  
  /// Check if this buffer supports the native handle (for encoder detection)
  bool SupportsNativeHandle() const { return true; }

  // Internal pool helpers (used by pooled copy and by the pooled lease API).
  static std::optional<Microsoft::WRL::ComPtr<ID3D11Texture2D>> AcquirePooledTexture(
      ID3D11Device* device,
      UINT width,
      UINT height,
      DXGI_FORMAT format);

  static void ReleasePooledTexture(PoolKey key,
                                  Microsoft::WRL::ComPtr<ID3D11Texture2D>&& tex);

 protected:
  D3D11TextureBuffer(
      Microsoft::WRL::ComPtr<ID3D11Texture2D> texture,
      Microsoft::WRL::ComPtr<ID3D11Device> device,
      int width,
      int height,
      DXGI_FORMAT format);

 private:
  // If true, this instance owns a pool-eligible texture and will return it on destruction.
  bool poolable_ = false;
  PoolKey pool_key_{};

  /// Create a staging texture for CPU readback
  bool CreateStagingTexture();
  
  /// Perform GPU→CPU readback into I420 buffer
  rtc::scoped_refptr<webrtc::I420BufferInterface> ReadbackToI420();

  Microsoft::WRL::ComPtr<ID3D11Texture2D> texture_;
  Microsoft::WRL::ComPtr<ID3D11Device> device_;
  Microsoft::WRL::ComPtr<ID3D11Texture2D> staging_texture_;
  
  int width_;
  int height_;
  DXGI_FORMAT format_;
  
  // Cached I420 buffer for repeated readback requests
  mutable std::mutex i420_cache_mutex_;
  mutable rtc::scoped_refptr<webrtc::I420BufferInterface> cached_i420_;
};

// ============================================================================
// C++ Functions for CXX Bridge (using opaque handle approach)
// All pointers are passed as uint64_t for CXX compatibility
// ============================================================================

/// Create a D3D11 frame buffer from raw texture and device handles
/// texture_handle: ID3D11Texture2D* cast to uint64_t
/// device_handle: ID3D11Device* cast to uint64_t
/// Returns opaque frame buffer handle, or 0 on failure
uint64_t create_d3d11_frame_buffer_from_handles(
    uint64_t texture_handle,
    uint64_t device_handle,
    uint32_t width,
    uint32_t height,
    uint32_t format);

/// Create a D3D11 frame buffer by copying from a source texture into an internal pooled texture.
///
/// source_texture_handle: ID3D11Texture2D* cast to uint64_t (borrowed; must be valid during call)
/// device_handle: ID3D11Device* cast to uint64_t (borrowed)
/// context_handle: ID3D11DeviceContext* cast to uint64_t (borrowed; must be valid during call)
/// Returns opaque frame buffer handle, or 0 on failure
uint64_t create_d3d11_frame_buffer_from_handles_pooled_copy(
    uint64_t source_texture_handle,
    uint64_t device_handle,
    uint64_t context_handle,
    uint32_t width,
    uint32_t height,
    uint32_t format);

/// Create a D3D11 frame buffer by scaling a source texture into an internal pooled texture
/// using the D3D11 Video Processor (video engine) when possible.
///
/// source_texture_handle: ID3D11Texture2D* cast to uint64_t (borrowed; must be valid during call)
/// device_handle: ID3D11Device* cast to uint64_t (borrowed)
/// context_handle: ID3D11DeviceContext* cast to uint64_t (borrowed; must be valid during call)
/// Returns opaque frame buffer handle, or 0 on failure.
uint64_t create_d3d11_frame_buffer_from_handles_pooled_vp_scale(
    uint64_t source_texture_handle,
    uint64_t device_handle,
    uint64_t context_handle,
    uint32_t src_width,
    uint32_t src_height,
    uint32_t dst_width,
    uint32_t dst_height,
    uint32_t format);

/// Acquire a pooled output texture "lease" for direct rendering into a WebRTC-owned pooled texture.
///
/// This is the building block for "direct-to-pooled shader scaling": Rust renders into the leased
/// pooled texture (as an RTV), then finalizes it into a `D3D11TextureBuffer` handle. This avoids
/// rendering into an intermediate `scaled_texture` and then doing a second CopyResource into the pool.
///
/// Returns 0 on failure. The returned handle must be released via `release_d3d11_pooled_texture_lease`
/// unless it is finalized via `finalize_d3d11_pooled_texture_lease_to_frame_buffer`.
uint64_t acquire_d3d11_pooled_texture_lease(
    uint64_t device_handle,
    uint32_t width,
    uint32_t height,
    uint32_t format);

/// Get an AddRef'd `ID3D11Texture2D*` for the given lease, returned as a u64.
/// The caller (Rust) adopts the returned COM ref and must release it (by dropping the COM wrapper).
uint64_t get_d3d11_pooled_texture_from_lease_addref(uint64_t lease_handle);

/// Finalize the lease into a WebRTC `D3D11TextureBuffer` and return the frame buffer handle.
/// This consumes the lease (it becomes invalid after this call).
uint64_t finalize_d3d11_pooled_texture_lease_to_frame_buffer(
    uint64_t lease_handle,
    uint32_t width,
    uint32_t height,
    uint32_t format);

/// Release a pooled texture lease without producing a frame buffer (returns the texture to pool).
/// Safe to call with 0.
void release_d3d11_pooled_texture_lease(uint64_t lease_handle);

/// Release a D3D11 frame buffer handle
void release_d3d11_frame_buffer(uint64_t handle);

/// Get info about a D3D11 frame buffer
D3D11TextureInfo get_d3d11_frame_buffer_info(uint64_t handle);

/// Check if D3D11 frame buffers are supported on this system
bool is_d3d11_frame_buffer_supported();

}  // namespace livekit_ffi

#endif  // _WIN32
